### ISSUE TITLE
How to preprocess the stimuli for the Pseudo-Saliency Dataset?

### ISSUE THREAD

**Issue by LJOVO** [gqding/SalFBNet#2]
Hi,

Thanks for releasing the Pseudo-Saliency dataset!
I was wondering how the images (stimuli) in this dataset should be preprocessed in this dataset because the spatial sizes of all the saliency maps are 640x480, but the stimuli from various datasets are not always of this size.

Thanks in advance.

**Comment by gqding** [comment]
Hi,

Thank you for your attention.
We resize the image to the size of the saliency map.

Bests,

**Comment by LJOVO** [comment]
Thank you for your reply！
